import type { ThemeConfig } from "ant-design-vue/es/config-provider/context";

export const appThemeTokens = {
  colorPrimary: "#b20000",
  colorLink: "#b94646",
  colorSuccess: "#52c41a",
  colorWarning: "#faad14",
  colorError: "#f5222d",
  colorText: "rgba(229, 229, 229, 0.75)",
  colorTextHeading: "rgba(255, 255, 255, 0.85)",
  colorTextSecondary: "rgba(0, 0, 0, 0.45)",
  colorTextDisabled: "#fff",
  colorBgBase: "#3d3d3d",
  colorBgContainer: "#000000",
  colorBgElevated: "#565656",
  colorBorder: "#c2c2c2",
  colorBorderSecondary: "#7b7b7b",
  colorCard: "#313131",
  colorHoverBg: "#313131",
  colorModalBg: "rgba(86, 86, 86, 0.8)",
  boxShadow: "0 2px 8px rgba(0, 0, 0, 0.15)",
} as const;

export const antdTheme: ThemeConfig = {
  token: {
    colorPrimary: appThemeTokens.colorPrimary,
    colorLink: appThemeTokens.colorLink,
    colorSuccess: appThemeTokens.colorSuccess,
    colorWarning: appThemeTokens.colorWarning,
    colorError: appThemeTokens.colorError,
    fontSize: 14,
    borderRadius: 0,
    colorText: appThemeTokens.colorText,
    colorTextHeading: appThemeTokens.colorTextHeading,
    colorTextSecondary: appThemeTokens.colorTextSecondary,
    colorTextDisabled: appThemeTokens.colorTextDisabled,
    colorBgBase: appThemeTokens.colorBgBase,
    colorBgContainer: appThemeTokens.colorBgContainer,
    colorBgElevated: appThemeTokens.colorBgElevated,
    colorBorder: appThemeTokens.colorBorder,
    colorBorderSecondary: appThemeTokens.colorBorderSecondary,
    controlOutline: "transparent",
    controlTmpOutline: "transparent",
    colorErrorOutline: "transparent",
    boxShadow: appThemeTokens.boxShadow,
  },
  components: {
    Button: {
      borderRadius: 0,
      colorBgContainer: appThemeTokens.colorBgContainer,
      colorText: appThemeTokens.colorText,
      colorBorder: appThemeTokens.colorBorder,
      defaultBg: appThemeTokens.colorBgContainer,
      defaultColor: appThemeTokens.colorText,
      colorPrimaryHover: appThemeTokens.colorPrimary,
      colorPrimaryActive: appThemeTokens.colorPrimary,
    },
    Card: {
      colorBgContainer: appThemeTokens.colorCard,
      colorFillAlter: appThemeTokens.colorBgElevated,
    },
    Dropdown: {
      colorBgElevated: appThemeTokens.colorBgElevated,
      controlItemBgHover: appThemeTokens.colorHoverBg,
    },
    Input: {
      colorBgContainer: appThemeTokens.colorBgContainer,
      colorText: appThemeTokens.colorText,
      borderRadius: 0,
    },
    Menu: {
      colorItemText: appThemeTokens.colorText,
      colorItemTextHover: appThemeTokens.colorTextHeading,
      colorItemTextSelected: appThemeTokens.colorTextHeading,
      colorItemTextDisabled: appThemeTokens.colorTextDisabled,
      colorItemBg: appThemeTokens.colorBgElevated,
      colorItemBgHover: appThemeTokens.colorHoverBg,
      colorItemBgActive: appThemeTokens.colorHoverBg,
      colorItemBgSelected: appThemeTokens.colorHoverBg,
      colorGroupTitle: appThemeTokens.colorText,
    },
    Modal: {
      contentBg: appThemeTokens.colorModalBg,
      borderRadiusLG: 0,
    },
    Progress: {
      defaultColor: appThemeTokens.colorPrimary,
      remainingColor: appThemeTokens.colorHoverBg,
    },
    Select: {
      colorBgContainer: appThemeTokens.colorBgContainer,
      colorBgElevated: appThemeTokens.colorBgElevated,
      optionSelectedBg: appThemeTokens.colorHoverBg,
      optionActiveBg: appThemeTokens.colorHoverBg,
      borderRadius: 0,
    },
    Table: {
      colorBgContainer: appThemeTokens.colorBgContainer,
      headerBg: appThemeTokens.colorBgContainer,
      rowHoverBg: appThemeTokens.colorHoverBg,
      borderColor: appThemeTokens.colorBorder,
      colorText: appThemeTokens.colorText,
    },
    Message: {
      contentBg: appThemeTokens.colorBgElevated,
    },
  },
};
