import type { ThemeConfig } from "ant-design-vue/es/config-provider/context";

export const appThemeTokens = {
  colorPrimary: "#b20000",
  colorPrimarySoft: "rgba(178, 0, 0, 0.18)",
  colorLink: "#b94646",
  colorLinkSoft: "rgba(185, 70, 70, 0.18)",
  colorSuccess: "#52c41a",
  colorSuccessSoft: "rgba(82, 196, 26, 0.18)",
  colorWarning: "#faad14",
  colorWarningSoft: "rgba(250, 173, 20, 0.18)",
  colorError: "#f5222d",
  colorErrorSoft: "rgba(245, 34, 45, 0.18)",
  colorText: "rgba(229, 229, 229, 0.75)",
  colorTextHeading: "rgba(255, 255, 255, 0.85)",
  colorTextSecondary: "rgba(229, 229, 229, 0.58)",
  colorTextDisabled: "#fff",
  colorBgBase: "#323233",
  colorBgContent: "#1E1E1E",
  colorBgContainer: "#000000",
  colorBgElevated: "#565656",
  colorAppBarHoverBg: "#252526",
  colorBorder: "rgba(255, 255, 255, 0.22)",
  colorBorderSecondary: "rgba(255, 255, 255, 0.1)",
  colorDivider: "rgba(255, 255, 255, 0.1)",
  colorCard: "#313131",
  colorHoverBg: "#313131",
  colorModalBg: "rgba(86, 86, 86, 0.8)",
  borderRadius: 0,
  boxShadow: "0 2px 8px rgba(0, 0, 0, 0.15)",
  boxShadowElevated: "1px 1px 1px 1px rgba(0, 0, 0, 0.5)",
  boxShadowElevatedStrong: "5px 5px 5px 1px rgba(0, 0, 0, 0.5)",
  colorCodeComment: "#6a9955",
  colorCodeKeyword: "#c586c0",
  colorCodeMuted: "#808080",
  colorCodeTag: "#569cd6",
  colorCodeAttribute: "#9cdcfe",
  colorCodeString: "#ce9178",
  titleBarHeight: 32,
} as const;

export const antdTheme: ThemeConfig = {
  token: {
    colorPrimary: appThemeTokens.colorPrimary,
    colorLink: appThemeTokens.colorLink,
    colorSuccess: appThemeTokens.colorSuccess,
    colorWarning: appThemeTokens.colorWarning,
    colorError: appThemeTokens.colorError,
    fontFamily: '"Segoe UI Variable", "Segoe UI", system-ui, sans-serif',
    fontSize: 12,
    lineHeight: 1.35,
    borderRadius: appThemeTokens.borderRadius,
    controlHeight: 26,
    controlHeightSM: 22,
    controlHeightLG: 30,
    padding: 8,
    paddingSM: 6,
    paddingXS: 4,
    paddingXXS: 2,
    margin: 8,
    marginSM: 6,
    marginXS: 4,
    marginXXS: 2,
    colorText: appThemeTokens.colorText,
    colorTextHeading: appThemeTokens.colorTextHeading,
    colorTextSecondary: appThemeTokens.colorTextSecondary,
    colorTextDisabled: appThemeTokens.colorTextDisabled,
    colorBgBase: appThemeTokens.colorBgBase,
    colorBgContainer: appThemeTokens.colorBgContainer,
    colorBgElevated: appThemeTokens.colorBgElevated,
    colorBorder: appThemeTokens.colorBorder,
    colorBorderSecondary: appThemeTokens.colorBorderSecondary,
    colorSplit: appThemeTokens.colorDivider,
    controlOutline: "transparent",
    controlTmpOutline: "transparent",
    colorErrorOutline: "transparent",
    boxShadow: appThemeTokens.boxShadow,
  },
  components: {
    Button: {
      borderRadius: appThemeTokens.borderRadius,
      controlHeight: 26,
      controlHeightSM: 22,
      controlHeightLG: 30,
      paddingInline: 8,
      paddingInlineSM: 6,
      paddingInlineLG: 10,
      colorBgContainer: appThemeTokens.colorBgContainer,
      colorText: appThemeTokens.colorText,
      colorBorder: "#111111",
      defaultBg: appThemeTokens.colorBgContainer,
      defaultColor: appThemeTokens.colorText,
      colorPrimaryHover: appThemeTokens.colorPrimary,
      colorPrimaryActive: appThemeTokens.colorPrimary,
    },
    Alert: {
      colorSuccessBg: "#0f1f12",
      colorSuccessBorder: "rgba(82, 196, 26, 0.45)",
      colorInfoBg: "#101820",
      colorInfoBorder: "rgba(64, 150, 255, 0.45)",
      colorWarningBg: "#1f1600",
      colorWarningBorder: "rgba(242, 204, 96, 0.45)",
      colorErrorBg: "#220f10",
      colorErrorBorder: "rgba(245, 34, 45, 0.48)",
      colorText: appThemeTokens.colorText,
      colorIcon: appThemeTokens.colorText,
      colorIconHover: appThemeTokens.colorTextHeading,
    },
    Card: {
      colorBgContainer: appThemeTokens.colorCard,
      colorFillAlter: appThemeTokens.colorBgElevated,
      paddingLG: 12,
    },
    Checkbox: {
      colorBgContainer: appThemeTokens.colorBgContainer,
      colorBorder: appThemeTokens.colorBorder,
    },
    Dropdown: {
      colorBgElevated: appThemeTokens.colorBgElevated,
      controlItemBgHover: appThemeTokens.colorHoverBg,
    },
    Input: {
      colorBgContainer: appThemeTokens.colorBgContainer,
      colorText: appThemeTokens.colorText,
      controlHeight: 26,
      controlHeightSM: 22,
      controlHeightLG: 30,
      paddingInline: 8,
      paddingInlineSM: 6,
      colorBorder: appThemeTokens.colorBorder,
      activeBorderColor: appThemeTokens.colorBorder,
      hoverBorderColor: appThemeTokens.colorBorder,
      borderRadius: appThemeTokens.borderRadius,
    },
    Menu: {
      controlHeight: 26,
      colorItemText: appThemeTokens.colorText,
      colorItemTextHover: appThemeTokens.colorTextHeading,
      colorItemTextSelected: appThemeTokens.colorTextHeading,
      colorItemTextDisabled: appThemeTokens.colorTextDisabled,
      colorItemBg: appThemeTokens.colorBgElevated,
      colorItemBgHover: appThemeTokens.colorHoverBg,
      colorItemBgActive: appThemeTokens.colorHoverBg,
      colorItemBgSelected: appThemeTokens.colorHoverBg,
      colorGroupTitle: appThemeTokens.colorText,
    },
    Modal: {
      contentBg: appThemeTokens.colorModalBg,
      borderRadiusLG: appThemeTokens.borderRadius,
    },
    Select: {
      colorBgContainer: appThemeTokens.colorBgContainer,
      colorBgElevated: appThemeTokens.colorBgElevated,
      controlHeight: 26,
      controlHeightSM: 22,
      controlHeightLG: 30,
      optionHeight: 26,
      optionPadding: "3px 8px",
      colorBorder: appThemeTokens.colorBorder,
      activeBorderColor: appThemeTokens.colorBorder,
      hoverBorderColor: appThemeTokens.colorBorder,
      optionSelectedBg: appThemeTokens.colorHoverBg,
      optionActiveBg: appThemeTokens.colorHoverBg,
      borderRadius: appThemeTokens.borderRadius,
    },
    Table: {
      colorBgContainer: appThemeTokens.colorBgContainer,
      headerBg: appThemeTokens.colorBgContainer,
      rowHoverBg: appThemeTokens.colorHoverBg,
      borderColor: appThemeTokens.colorDivider,
      colorText: appThemeTokens.colorText,
      cellPaddingBlock: 6,
      cellPaddingBlockSM: 4,
      cellPaddingInline: 8,
      cellPaddingInlineSM: 6,
      headerBorderRadius: appThemeTokens.borderRadius,
    },
    Form: {
      itemMarginBottom: 10,
    },
    Message: {
      contentBg: appThemeTokens.colorBgElevated,
    },
  },
};
