const ERROR_CODES = {
    UNKNOWN: 'UNKNOWN',
    API_FUNCTION_UNDEFINED: 'API_FUNCTION_UNDEFINED',
    ILLEGAL_IPC_CHANNEL: 'ILLEGAL_IPC_CHANNEL',
    PATH_NOT_FOUND: 'PATH_NOT_FOUND',
    PATH_PERMISSION_DENIED: 'PATH_PERMISSION_DENIED',
    PATH_ALREADY_EXISTS: 'PATH_ALREADY_EXISTS',
    PATH_BUSY: 'PATH_BUSY',
    DIRECTORY_NOT_EMPTY: 'DIRECTORY_NOT_EMPTY',
    PATH_INVALID: 'PATH_INVALID',
    FILE_SYSTEM_ERROR: 'FILE_SYSTEM_ERROR',
    DATABASE_OPERATION_FAILED: 'DATABASE_OPERATION_FAILED',
    SERVER_FOLDER_EMPTY: 'SERVER_FOLDER_EMPTY',
    SOURCE_PRESET_NOT_FOUND: 'SOURCE_PRESET_NOT_FOUND',
    ACTIVE_PRESET_NOT_FOUND: 'ACTIVE_PRESET_NOT_FOUND',
    MISSION_FOLDER_INVALID: 'MISSION_FOLDER_INVALID',
    UNSUPPORTED_CE_TYPE: 'UNSUPPORTED_CE_TYPE',
    XML_ROOT_MISMATCH: 'XML_ROOT_MISMATCH',
} as const;

type AppErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

export {
    ERROR_CODES,
    type AppErrorCode
};
